# ベースイメージとして公式のNginxイメージを使用
FROM nginx:alpine

# 静的ファイルをコピー
COPY ./out /usr/share/nginx/html

# Nginxの設定ファイルを上書き
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Nginxを起動
CMD ["nginx", "-g", "daemon off;"]
